### PR TITLE
Fix: tokenize the latest right curly brace (fixes #403)

### LINKED ISSUE #403: espree.tokenize doesn't tokenize } if it's last token
Espree doesn't tokenize `}`

```js
espree.tokenize('{}') // 1st
espree.tokenize('}') // 2nd
espree.tokenize('{}?') // 3rd
espree.tokenize('{\n}}') // 4th
```
output is:
```js
// 1st
[ Token { type: 'Punctuator', value: '{', start: 0, end: 1 } ]
// 2nd
[]
// 3rd
[ Token { type: 'Punctuator', value: '{', start: 0, end: 1 },
  Token { type: 'Punctuator', value: '}', start: 1, end: 2 },
  Token { type: 'Punctuator', value: '?', start: 2, end: 3 } ]
// 4th
[ Token { type: 'Punctuator', value: '{', start: 0, end: 1 },
  Token { type: 'Punctuator', value: '}', start: 2, end: 3 } ]
```

### PR DESCRIPTION
**Pull request by finico**
There is a logic in `TokenTranslator::onToken` about the latest curly brace
https://github.com/eslint/espree/blob/6ebc21947166399a0b4918d4a1beb9d610650336/lib/token-translator.js#L196-L204
But it executes only at first `eof` token (it seems strange that the first token is `eof`, but it comes from Acorn's init state)
I've added a call of `next` for the `TokenTranslator::onToken` to be executed with the last `eof` token

And I've noticed two failed tests, but they've already fixed at #416

### CODE REVIEW

**Comment by kaicataldo** [comment]
Hi, thanks for contributing. It looks like there are some tests failing - do you mind fixing those so that we can review this?

**Comment by finico** [comment]
Hi @kaicataldo , thank you for quick response.
As I mentioned in the description, these tests were fixed in 416th pull request.
We can wait till it will be merged, then I will rebase my branch on upstream

File: lib/espree.js [hunk 1]
```diff
@@ -174,6 +174,9 @@ module.exports = () => Parser => class Espree extends Parser {
             this.next();
         } while (this.type !== tokTypes.eof);
 
+        // it's a call for the latest `eof` token
```
Comment (kaicataldo) [inline lib/espree.js]: I think the word "latest" is confusing here because it looks like `this.next()` will continue returning muliple `eof` tokens. I wonder if something like the following would be clearer:

```suggestion
        // Consume the final eof token
```

**Comment by platinumazure** [comment]
Hi @finico, would you mind merging/rebasing upstream changes please? Thanks!

**Comment by finico** [comment]
@platinumazure @kaicataldo done

File: tests/lib/tokenize.js [hunk 2]
```diff
@@ -199,4 +199,16 @@ describe("tokenize()", () => {
         espree.tokenize("foo", Object.freeze({ ecmaFeatures: Object.freeze({}) }));
     });
 
+    it("should produce tokens when } is the last token", () => {
```
Comment (kaicataldo) [inline tests/lib/tokenize.js]: Do you mind adding a comment with a link to the relevant issue here so that future contributors have some context as to why this test exists?

Comment (finico) [reply tests/lib/tokenize.js]: I've added, but I'm not sure about the description

File: tests/lib/tokenize.js [hunk 3]
```diff
@@ -199,4 +199,20 @@ describe("tokenize()", () => {
         espree.tokenize("foo", Object.freeze({ ecmaFeatures: Object.freeze({}) }));
     });
 
+    /**
+     * Make sure we tokenize closing curly brace in a block statement
```
Comment (platinumazure) [inline tests/lib/tokenize.js]: Based on what you understand of the issue, would this be an improvement?

```suggestion
     * Make sure we tokenize closing curly brace in a block statement at end of file
```

File: tests/lib/tokenize.js (hunk 2 above)
Comment (kaicataldo) [reply tests/lib/tokenize.js]: Sorry, could have been clearer. This is fine, but I also think a comment that just says `// https://github.com/eslint/espree/issues/403` would suffice!

File: tests/lib/tokenize.js (hunk 3 above)
Comment (finico) [reply tests/lib/tokenize.js]: I think so

File: tests/lib/tokenize.js (hunk 2 above)
Comment (finico) [reply tests/lib/tokenize.js]: Sorry, if you would suggest me what to add, I will add

File: tests/lib/tokenize.js (hunk 3 above)
Comment (finico) [reply tests/lib/tokenize.js]: added

File: tests/lib/tokenize.js (hunk 2 above)
Comment (kaicataldo) [reply tests/lib/tokenize.js]: This is fine! Thanks for adding the comment.
