### PR TITLE
Fix: Various Arrow Function Issues (fixes #187, #145 and #172)

### LINKED ISSUE #187: Rest Params and Arrow Functions Not working
```
 require('./espree').parse('(a, ...b) => a[0]', {ecmaFeatures: { arrowFunctions: true, restParams: true }})
Error: Line 1: Unexpected token =>
    at throwError (/Users/jamuferguson/dev/espree/espree.js:2070:17)
    at throwUnexpected (/Users/jamuferguson/dev/espree/espree.js:2133:5)
    at reinterpretAsDestructuredParameter (/Users/jamuferguson/dev/espree/espree.js:3453:9)
    at reinterpretAsCoverFormalsList (/Users/jamuferguson/dev/espree/espree.js:3312:13)
    at parseAssignmentExpression (/Users/jamuferguson/dev/espree/espree.js:3534:22)
    at parseExpression (/Users/jamuferguson/dev/espree/espree.js:3568:16)
    at parseExpressionStatement (/Users/jamuferguson/dev/espree/espree.js:3763:16)
    at parseStatement (/Users/jamuferguson/dev/espree/espree.js:4290:44)
    at parseSourceElement (/Users/jamuferguson/dev/espree/espree.js:5176:16)
    at parseSourceElements (/Users/jamuferguson/dev/espree/espree.js:5209:25)
```

This is possibly related to #132 and was discovered while working on eslint/eslint#3353

### PR DESCRIPTION
**Pull request by xjamundx**
I can't remember the correct way If you want these squashed into a single commit or not.

I'll comment below on some things I wanted feedback on...

Fixes #187, #145 and #172

### CODE REVIEW

File: espree.js [hunk 1]
```diff
@@ -4398,7 +4403,7 @@ function parseFunctionSourceElements() {
     oldInIteration = state.inIteration;
     oldInSwitch = state.inSwitch;
     oldInFunctionBody = state.inFunctionBody;
-    oldParenthesisCount = state.parenthesizedCount;
```
Comment (xjamundx) [inline espree.js]: This seemed like a typo, because half the time it's spelled differently, so I changed it. `parenthesizedCount` vs `parenthesisCount`. They are the same thing right?

File: espree.js [hunk 2]
```diff
@@ -3535,6 +3539,7 @@ function parseAssignmentExpression() {
         }
 
         if (params) {
+            state.parenthesisCount--;
```
Comment (xjamundx) [inline espree.js]: This was the fix for the nested default params issue (`(a, b=(c)=>c) => {}`). All of the tests pass yes, but I'm not super duper confident I understand how the `parenthsisCount` stuff works. What I'm trying to say here is, if you're inside an arrow function param let's not worry about 1 set of parens when it comes to determining if other things are arrow functions, etc.

File: espree.js (hunk 1 above)
Comment (nzakas) [inline espree.js]: I believe so.

File: espree.js [hunk 3]
```diff
@@ -3356,10 +3356,15 @@ function reinterpretAsCoverFormalsList(expressions) {
 
 function parseArrowFunctionExpression(options, marker) {
     var previousStrict, body;
+    var arrowStart = lineNumber;
 
     expect("=>");
     previousStrict = strict;
 
+    if (lineNumber > arrowStart) {
+        throwError({}, Messages.UnexpectedToken, "=>");
```
Comment (nzakas) [inline espree.js]: Wouldn't the token after the arrow be the unexpected one?

Comment (xjamundx) [inline espree.js]: In this case the `=>` is on a new line by itself and so it's not expected, at least not there. Let me know if that doesn't sound right.

```
var a = ()
	=> 0; 
```

Comment (nzakas) [inline espree.js]: Oh I see, makes sense.

**Comment by nzakas** [comment]
Lgtm
